CREATE TABLE LOCATIONS (
  LOCATION_ID    NUMBER PRIMARY KEY,
  STREET_ADDRESS VARCHAR2(40),
  POSTAL_CODE    VARCHAR2(12),
  CITY           VARCHAR2(30) NOT NULL,
  STATE_PROVINCE  VARCHAR2(25)
);


CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID    NUMBER PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(30),
  LOCATION_ID    NUMBER
);

CREATE TABLE JOBS (
  JOB_ID VARCHAR2(30) PRIMARY KEY,
  JOB_TITLE VARCHAR2(35),
  MIN_SALARY NUMBER,
  MAX_SALARY NUMBER
);

CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR2(20),
  LAST_NAME VARCHAR2(25) NOT NULL ,
  EMAIL VARCHAR2(25) NOT NULL,
  PHONE_NUMBER VARCHAR2(20),
  HIRE_DATE DATE NOT NULL ,
  JOB_ID VARCHAR2(30) NOT NULL ,
  SALARY NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID NUMBER,
  DEPARTMENT_ID NUMBER
);

ALTER TABLE EMPLOYEES ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);
